# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "ivanmartovytskyi/telebot"
  tag: "v1.0.6-01bf0ec"
  arch: "amd64"
  os: "linux"
secret:
  name: "telebot"
  env: "TELE_TOKEN"
  key: "token"
