# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "ivanmartovytskyi"
  tag: "v1.0.6-33bb6fb"
  arch: "amd64"
  os: "linux"
secret:
  name: "telebot"
  env: "TELE_TOKEN"
  key: "token"
