name: TELEBOT-CICD

on: push

env:
  TARGETARCH: amd64
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push
        env:
          APP: "telebot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push TARGETARCH=$TARGETARCH

      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH
